[package]
name = "bwminimaprender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
image = { version = "*", features = ["png"] }
lazy_static = "*"
tracing = "*"
